on:
  push:
  workflow_dispatch:

jobs:
  hello_world:
    runs-on: ubuntu-latest
    name: say hello to my little firend
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: chaoqunya/hello-world-composite-action@v2
        with:
          who-to-greet: "Chaos"
      - run: echo random-number ${{ steps.foo.outputs.random-number }} test
        shell: bash
      - id: bar
        uses: ./.github/actions/hello-world
        with:
          who-to-greet: "Chaos"
      - run: echo random-number ${{ steps.bar.outputs.random-number }} test
        shell: bash
